### ISSUE TITLE
Failure when using dense_stereo via command line  in PMVS workspace

### ISSUE THREAD

**Issue by pogilon** [colmap/colmap#162]
On the latest commit, when trying to conduct dense stereo using the command line and PMVS workspace format I get the following error. Could you please help me resolve it? Thanks! (Check failed: file.is_open() pmvs/stereo/patch-match.cfg)

Reading workspace...
Reading configuration...
F0628 09:37:41.965101 10148 patch_match.cc:285] Check failed: file.is_open() pmvs/stereo/patch-match.cfg
*** Check failure stack trace: ***
    @     0x7f3976a095cd  google::LogMessage::Fail()
    @     0x7f3976a0b433  google::LogMessage::SendToLog()
    @     0x7f3976a0915b  google::LogMessage::Flush()
    @     0x7f3976a0be1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x573e29  colmap::mvs::PatchMatchController::ReadProblems()
    @           0x576334  colmap::mvs::PatchMatchController::Run()
    @           0x67aa9c  colmap::Thread::RunFunc()
    @     0x7f397395cc80  (unknown)
    @     0x7f39762a56ba  start_thread
    @     0x7f39730c23dd  clone
    @              (nil)  (unknown)

**Comment by ahojnnes** [comment]
I will check later this week, thanks for reporting.

**Comment by pogilon** [comment]
@ahojnnes  thanks. I am looking forward to it :)

**Comment by pogilon** [comment]
@ahojnnes thank you for your support and to continue improving this algorithm. What do yo you think could be the problem here?

**Comment by ahojnnes** [comment]
I will only have time to look into this later this or next week. But it is on my todo list.

**Comment by pogilon** [comment]
Hey @ahojnnes. Thank you for all your efforts. Do think this is something that could be addressed anytime soon? I would really appreciate as I am trying to connect some algorithms that output in PMVS format with COLMAP. Please let me know and Thanks!

**Comment by ahojnnes** [comment]
This is fixed in the latest commit in the dev branch. Let me know if it works for you. Thanks.

**Comment by pogilon** [comment]
Thank you @ahojnnes. Now there are other bugs. Please see below.

**When running Colmap-photometric only on the PMVS workspace (no CMVS or genOption):**

- Colmap uses all images in the reconstruction as src_image_ids, instead of using the vis.dat information to only use the ones stated there for each image.
-The fusion process gives the following error:
"
Reading workspace...
Reading configuration...
WARNING: Ignoring image 00000000.jpg, because input does not exist.
WARNING: Ignoring image 00000001.jpg, because input does not exist.
WARNING: Ignoring image 00000002.jpg, because input does not exist.
WARNING: Ignoring image 00000003.jpg, because input does not exist.
WARNING: Ignoring image 00000004.jpg, because input does not exist.
WARNING: Ignoring image 00000005.jpg, because input does not exist.
WARNING: Ignoring image 00000006.jpg, because input does not exist.
WARNING: Ignoring image 00000007.jpg, because input does not exist.
WARNING: Ignoring image 00000008.jpg, because input does not exist.
WARNING: Ignoring image 00000009.jpg, because input does not exist.
WARNING: Ignoring image 00000010.jpg, because input does not exist.
WARNING: Ignoring image 00000011.jpg, because input does not exist.
WARNING: Ignoring image 00000012.jpg, because input does not exist.
WARNING: Ignoring image 00000013.jpg, because input does not exist.
WARNING: Ignoring image 00000014.jpg, because input does not exist.
"

****When running CMVS-Colmap-photometric only on the PMVS workspace:****

- Colmap uses all images determined by CMVS to be used in the reconstruction as src_image_ids, instead of using the vis.dat information to only use the ones stated there for each image.
- The fusion process gets stuck fusing the depths maps. It tries to fuse all images, including the ones discarded during the CMVS process.

**Comment by ahojnnes** [comment]
With the latest commit in the dev branch, COLMAP automatically selects a subset as source images when using the PMVS workspace format. Thanks for reporting this problem.

Regarding the other issues, I assume you are passing the wrong paths to the fusion?

**Comment by pogilon** [comment]
@ahojnnes thank you. The new procedure takes a subset of all the images when using the PMVS workspace, however, it still does not limit the source images to be part of the specific small sub-group divided by CMVS. Meaning that, during densification, it would pick source images that are outside a sub-group, if they make sense when processing all the images altogether. As a result, I believe this is also causing the fusion step to get stuck in "Reading Configuration".

Thanks.

**Comment by pogilon** [comment]
@ahojnnes following the previous comment. I checked the fusion path, and maybe I had the wrong one. However, now when trying to fuse the data I get the following error:
StereoFusion::Options
---------------------
max_image_size: -1
min_num_pixels: 5
max_num_pixels: 10000
max_traversal_depth: 100
max_reproj_error: 2
max_depth_error: 0.01
max_normal_error: 10
check_num_images: 50
cache_size: 32

Reading workspace...
Reading configuration...
F0813 17:59:29.534927  9832 misc.cc:241] Check failed: file.is_open() pmvs/stereo/fusion.cfg
*** Check failure stack trace: ***
    @     0x7fc35741e5cd  google::LogMessage::Fail()
    @     0x7fc357420433  google::LogMessage::SendToLog()
    @     0x7fc35741e15b  google::LogMessage::Flush()
    @     0x7fc357420e1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x59e93f  colmap::ReadTextFileLines()
    @           0x53dfca  colmap::mvs::StereoFusion::Run()
    @           0x5bfd8c  colmap::Thread::RunFunc()
    @     0x7fc355650c80  (unknown)
    @     0x7fc356ca66ba  start_thread
    @     0x7fc354db63dd  clone
    @              (nil)  (unknown)
./run-cmvs-colmap-photometric.sh: line 24:  9831 Aborted                 (core dumped) $COLMAP_EXE_PATH/dense_fuser --workspace_path pmvs --workspace_format PMVS --input_type photometric --output_path pmvs/$option_name-fused.ply

**Comment by pogilon** [comment]
@ahojnnes, any updates? I am really excited to try this out. About the path for the fusion, I think I am passing the right path. If I put a different one then the software does not find the bundle.rd.out file. When I pass the right path it just stays as 
"Reading workspace...
Reading configuration...". Maybe there is something with the internal configuration of the paths? By the way, is there a converter PMVs to COLMAP workspace? Thanks.

**Comment by ahojnnes** [comment]
@pogilon This should be fixed in the "dev" branch now. Can you please recompile, check on your data, and report back? Thannks.

**Comment by pogilon** [comment]
@ahojnnes I just tried again. The depth map step seems to be working accordingly now. The fusion step is giving the following error:

Reading workspace...
Reading configuration...
F0825 08:40:12.085535 26059 misc.cc:241] Check failed: file.is_open() pmvs/stereo/fusion.cfg
*** Check failure stack trace: ***
    @     0x7f031c0f75cd  google::LogMessage::Fail()
    @     0x7f031c0f9433  google::LogMessage::SendToLog()
    @     0x7f031c0f715b  google::LogMessage::Flush()
    @     0x7f031c0f9e1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x5a171f  colmap::ReadTextFileLines()
    @           0x540912  colmap::mvs::StereoFusion::Run()
    @           0x5c2b6c  colmap::Thread::RunFunc()
    @     0x7f031a329c80  (unknown)
    @     0x7f031b97f6ba  start_thread
    @     0x7f0319a8f3dd  clone
    @              (nil)  (unknown)
./run-cmvs-colmap-photometric.sh: line 28: 26058 Aborted                 (core dumped) $COLMAP_EXE_PATH/dense_fuser --workspace_path pmvs --workspace_format PMVS --input_type photometric --output_path pmvs/$option_name-fused.ply

**Comment by pogilon** [comment]
@ahojnnes  I believe the error here is that it is trying to locate the "fusion.cfg" file in "pmvs/stereo" however, it is now in "pmvs/stereo-$option_name".

**Comment by pogilon** [comment]
@ahojnnes So, I change the "default" directory name from  "pmvs/stereo-$option_name" to "pmvs/stereo" and it went through the "Reading Configuration" stage. However, (see below for error), the fusion process gets stuck because it tries to fuse images that are not part of the CMVS cluster being fused. The whole image set was 24 images, then 2 images were discarded during the CMVS process. As you can see it tried to fuse more than 22 images and got stuck there.

Reading workspace...
Reading configuration...
Fusing image [1/24] in 5.778s (18277 points)
Fusing image [2/24] in 0.094s (21423 points)
Fusing image [3/24] in 0.054s (22565 points)
Fusing image [4/24] in 0.052s (24005 points)
Fusing image [5/24] in 0.035s (24288 points)
Fusing image [6/24] in 0.048s (25258 points)
Fusing image [7/24] in 0.048s (26328 points)
Fusing image [8/24] in 0.145s (34143 points)
Fusing image [9/24] in 0.055s (36126 points)
Fusing image [10/24] in 0.060s (38774 points)
Fusing image [11/24] in 0.030s (39479 points)
Fusing image [12/24] in 0.032s (40520 points)
Fusing image [13/24] in 0.028s (41313 points)
Fusing image [14/24] in 0.028s (42467 points)
Fusing image [15/24] in 0.021s (43058 points)
Fusing image [16/24] in 0.018s (43273 points)
Fusing image [17/24] in 0.018s (43296 points)
Fusing image [18/24] in 0.011s (43302 points)
Fusing image [19/24] in 0.016s (43714 points)
Fusing image [20/24] in 0.014s (44076 points)
Fusing image [21/24] in 0.012s (44153 points)
Fusing image [22/24] in 0.008s (44153 points)



Reading workspace...
Reading configuration...
Fusing image [1/24] in 5.778s (18277 points)
Fusing image [2/24] in 0.094s (21423 points)
Fusing image [3/24] in 0.054s (22565 points)
Fusing image [4/24] in 0.052s (24005 points)
Fusing image [5/24] in 0.035s (24288 points)
Fusing image [6/24] in 0.048s (25258 points)
Fusing image [7/24] in 0.048s (26328 points)
Fusing image [8/24] in 0.145s (34143 points)
Fusing image [9/24] in 0.055s (36126 points)
Fusing image [10/24] in 0.060s (38774 points)
Fusing image [11/24] in 0.030s (39479 points)
Fusing image [12/24] in 0.032s (40520 points)
Fusing image [13/24] in 0.028s (41313 points)
Fusing image [14/24] in 0.028s (42467 points)
Fusing image [15/24] in 0.021s (43058 points)
Fusing image [16/24] in 0.018s (43273 points)
Fusing image [17/24] in 0.018s (43296 points)
Fusing image [18/24] in 0.011s (43302 points)
Fusing image [19/24] in 0.016s (43714 points)
Fusing image [20/24] in 0.014s (44076 points)
Fusing image [21/24] in 0.012s (44153 points)
Fusing image [22/24] in 0.008s (44153 points)

**Comment by ahojnnes** [comment]
I will check this as soon as I get back from my travel in 8 days. Thanks for the feedback.

**Comment by ahojnnes** [comment]
Hi, checkout the latest commit. This should be fixed now. You can pass a ``--pmvs_option_name`` parameter to the fusion stage now.

**Comment by pogilon** [comment]
@ahojnnes , the directory works well now. However, I see that still, the fusion process is not working properly. It still tries to fuse all the images instead of the images pertaining to the CMVS cluster, and therefore it gets stuck because it looks for depth maps that are not computed. For example, I aligned a set of 12 images and conducted CMVS which reduced the set to 9 images. However, the Fusion step tries to fuse 12 images instead of the 9. See below error:

StereoFusion::Options
---------------------
max_image_size: -1
min_num_pixels: 5
max_num_pixels: 10000
max_traversal_depth: 100
max_reproj_error: 2
max_depth_error: 0.01
max_normal_error: 10
check_num_images: 50
cache_size: 32

Reading workspace...
Reading configuration...
Fusing image [1/12] in 2.847s (7294 points)
Fusing image [2/12] in 0.052s (9993 points)
Fusing image [3/12] in 0.032s (11409 points)
Fusing image [4/12] in 0.032s (13254 points)
Fusing image [5/12] in 0.030s (15300 points)
Fusing image [6/12] in 0.022s (16466 points)
Fusing image [7/12] in 0.016s (16829 points)
Fusing image [8/12] in 0.011s (16836 points)
Fusing image [9/12] in 0.007s (16836 points)

**Comment by ahojnnes** [comment]
Can you send me your corresponding PMVS/CMVS option files and the fusion.cfg? Thanks.

**Comment by pogilon** [comment]
Please see attached. Thanks!

[files.zip](https://github.com/colmap/colmap/files/1275479/files.zip)

**Comment by ahojnnes** [comment]
Can you also send me the whole PMVS folder? Thanks.

**Comment by pogilon** [comment]
Hi @ahojnnes . See attached the PMVS folder (https://drive.google.com/open?id=0B91Mv2MCT423aUtPNU1wdUw0eEE). 

This example contains 12 images from the South Building dataset, from which CMVS discards 4 images. In this example, the fusion step gets struck at early in the process when it tries to fuse one of the discarded images. Please let me know if anything. Thanks.

**Comment by ahojnnes** [comment]
This should be fixed in the last commit in the dev branch. Thanks for the help.
